spring:
  jpa:
    show-sql: false

  flyway:
    validate-on-migrate: true

server:
  error:
    include-stacktrace: never
    include-message: always
    include-binding-errors: never

logging:
  level:
    root: INFO
    com.iolabs.salescore: INFO
    org.springframework.security: WARN

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
